[advisories]
version = 2
yanked = "deny"
ignore = [
    # paste no longer maintained, but not critical
    "RUSTSEC-2024-0436",
]

[licenses]
version = 2
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Unicode-3.0",
]

[[licenses.exceptions]]
allow = ["GPL-3.0-only"]
crate = "pika-backup"

[[licenses.exceptions]]
allow = ["GPL-3.0-only"]
crate = "pika-backup-common"

[[licenses.exceptions]]
allow = ["GPL-3.0-only"]
crate = "pika-backup-monitor"
